#!/bin/sh

docker rm server3-php5
docker rmi keithy/alpine-apache-php:php5.6.33

docker rm server3-php7
docker rmi  keithy/alpine-apache-php:php7.2.1

docker rm server3-staging-toolkit
docker rmi keithy/website-staging-toolkit:latest

cd docker-ssh-agent
./run.sh -D
