#!/bin/sh

cd docker-ssh-agent
./run.sh

docker run -d -p 4056:80 \
    --name server3-php5 \
    --hostname server3-php5 \
    --volumes-from=ssh-agent -e SSH_AUTH_SOCK=/.ssh-agent/socket \
    -v /Users/Shared/server3:/server \
    -v /Users/Shared/server3-php5/backup:/backup \
    -v /Users/Shared/server3-php5/web:/web \
    -v /Users/Shared/server3/var/www:/var/www \
    -e "MYSQL_HOST=edit3.pul" \
    keithy/alpine-apache-php:php5.6.33 \
    /boot.sh

docker run -d -p 4072:80 \
    --name server3-php7 \
    --hostname server3-php7 \
    --volumes-from=ssh-agent -e SSH_AUTH_SOCK=/.ssh-agent/socket \
    -v /Users/Shared/server3:/server \
    -v /Users/Shared/server3-php7/backup:/backup \
    -v /Users/Shared/server3-php7/web:/web \
    -v /Users/Shared/server3/var/www:/var/www \
    -e "MYSQL_HOST=edit3.pul" \
    keithy/alpine-apache-php:php7.2.1 \
    /boot.sh




