#!/bin/sh

#production mimic
docker stop server1-php5
docker stop server2-php5
docker stop server3-php5

#rehearsal
#docker stop server1-php5-R
#docker stop server2-php5-R
docker stop server3-php5-R

#new
docker stop server3-php7
docker stop server3-php7-R
docker stop server3-php7-D
