#!/usr/bin/env ruby

# gem install net-ssh-shell
# https://github.com/mitchellh/net-ssh-shell
# require 'net/ssh'
# require 'net/ssh/shell'
# 
# Net::SSH::start('server', 'keith') do |ssh|
#   ssh.shell do |sh|
#     sh.execute( "cd /Applications")
#     sh.execute( "ls -l" ) { | proc |
# 
#       proc.on_output { | proc, data|
#       puts data
#       }
#     }
#  	puts "Yeah"
#     p=sh.execute "ls | grep .app"
#     puts "Exit Status:#{p.exit_status}"
#     puts "Command Executed:#{p.command}"
#     
#     sh.execute( 'exit')
#   end
# 
# end

require 'net/ssh'
require 'net/ssh/shell'

Net::SSH::start('server', 'keith') do |ssh|
  ssh.shell do |sh|
    sh.execute "cd /usr/local"
    sh.execute "pwd"
    sh.execute "export FOO=bar"
    sh.execute "echo $FOO"
    p=sh.execute "grep dont /tmp/notexist"
    puts "Exit Status:#{p.exit_status}"
    puts "Command Executed:#{p.command}"
  end
   ssh.shell do |sh|
    sh.execute "cd /usr/local"
    sh.execute "pwd"
    sh.execute "export FOO=bar"
    sh.execute "echo $FOO"
    p=sh.execute "grep dont /tmp/notexist"
    puts "Exit Status:#{p.exit_status}"
    puts "Command Executed:#{p.command}"
  end
end