#!/bin/sh

cd docker-ssh-agent
./run.sh

# server 1 php7 production mimic server
    --volumes-from=ssh-agent -e SSH_AUTH_SOCK=/.ssh-agent/socket \
    -v /Users/Shared/mimic-config-shared:/shared \
	-p 1072:80 \
    --name server1-php7 \
    --hostname server1-php7 \
    -v /Users/Shared/mnt/test1-editadmin:/server \
    -v /Users/Shared/mimic-logs/mimic-php7-server1:/logs \
    -v /Users/Shared/mimic-webroots/web-php7-server1:/web \
    -v /Users/Shared/mnt/test1-editadmin/var/www/html:/var/www/html \
    -v /Users/Shared/mnt/test1-editadmin/var/www/html:/var/www/production \
    -v /Users/Shared/mnt/test1-editadmin/home/editadmin/rehearsal/master:/var/www/rehearsal \
    -e "MYSQL_HOST=test1.pul" \
    -e "PROXY_LIVE_HOST=test1.pul" \
    -p 1111:8080 \
    -p 1443:8443 \
    keithy/alpine-apache-php:php7.2 \
    /boot.sh

# server 2 php5 production mimic server
docker run -d \
    --volumes-from=ssh-agent -e SSH_AUTH_SOCK=/.ssh-agent/socket \
    -v /Users/Shared/mimic-config-shared:/shared \
	-p 2072:80 \
    --name server2-php7 \
    --hostname server2-php7 \
    --volumes-from=ssh-agent -e SSH_AUTH_SOCK=/.ssh-agent/socket \
    -v /Users/Shared/mnt/test2-editadmin:/server \
    -v /Users/Shared/mimic-logs/mimic-php7-server2:/logs \
    -v /Users/Shared/mimic-webroots/web-php7-server2:/web \
    -v /Users/Shared/mnt/test2-editadmin/var/www/html:/var/www/html \
    -v /Users/Shared/mnt/test2-editadmin/var/www/html:/var/www/production \
    -v /Users/Shared/mnt/test2-editadmin/home/editadmin/rehearsal/master:/var/www/rehearsal \
    -e "MYSQL_HOST=test2.pul" \
    -e "PROXY_LIVE_HOST=test2.pul" \
    -p 2222:8080 \
    -p 2443:8443  \
    keithy/alpine-apache-php:php7.2 \
    /boot.sh

#server 3 php7 production server
docker run -d \
	--volumes-from=ssh-agent -e SSH_AUTH_SOCK=/.ssh-agent/socket \
    -v /Users/Shared/mimic-config-shared:/shared \
	-p 3072:80 \
	--name server3-php7 \
	--hostname server3-php7 \
    -v /Users/Shared/mnt/server3-editadmin:/server \
	-v /Users/Shared/mimic-logs/mimic-php7-server3:/logs \
	-v /Users/Shared/mimic-webroots/web-php7-server3:/web \
    -v /Users/Shared/mnt/test3-editadmin/var/www/html:/var/www/html \
    -v /Users/Shared/mnt/test3-editadmin/var/www/html:/var/www/production \
    -v /Users/Shared/development/rehearsal/master:/var/www/rehearsal \
    -e "MYSQL_HOST=test3.pul" \
    keithy/alpine-apache-php:php7.2 \
    /boot.sh

#server 3 php7 rehearsal server
docker run -d \
	--volumes-from=ssh-agent -e SSH_AUTH_SOCK=/.ssh-agent/socket \
    -v /Users/Shared/mimic-config-shared:/shared \
	-p 3172:80 \
	--name server3-php7-R \
	--hostname server3-php7-R \
    -v /Users/Shared/mnt/server3-editadmin:/server \
	-v /Users/Shared/mimic-logs/mimic-php7-server3R:/logs \
	-v /Users/Shared/mimic-webroots/web-php7-server3R:/web \
    -v /Users/Shared/development/rehearsal/13.0.1_PHP_7:/var/www/html \
    -v /Users/Shared/mnt/test3-editadmin/var/www/html:/var/www/production \
    -v /Users/Shared/development/rehearsal/13.0.1_PHP_7:/var/www/rehearsal \
    -e "MYSQL_HOST=test3.pul" \
    keithy/alpine-apache-php:php7.2 \
    /boot.sh
    
#server 3 php7 development server
docker run -d \
	--volumes-from=ssh-agent -e SSH_AUTH_SOCK=/.ssh-agent/socket \
    -v /Users/Shared/mimic-config-shared:/shared \
	-p 3272:80 \
	--name server3-php7-D \
	--hostname server3-php7-D \
    -v /Users/Shared/mnt/server3-editadmin:/server \
	-v /Users/Shared/mimic-logs/mimic-php7-server3D:/logs \
	-v /Users/Shared/mimic-webroots/web-php7-server3D:/web \
    -v /Users/Shared/development/rehearsal/13.0.1_PHP_7:/var/www/html \
    -v /Users/Shared/mnt/test3-editadmin/var/www/html:/var/www/production \
    -v /Users/Shared/development/rehearsal/13.0.1_PHP_7:/var/www/rehearsal \
    -e "MYSQL_HOST=test3.pul" \
    keithy/alpine-apache-php:php7.2 \
    /boot.sh
 




