#!/bin/sh

#production mimic
docker start server1-php7
docker start server2-php7
docker start server3-php7

#rehearsal
docker start server1-php7-R
docker start server2-php7-R
docker start server3-php7-R

#development
docker start server1-php7-D
docker start server2-php7-D
docker start server3-php7-D
