#!/bin/sh

#production mimic
docker stop server1-php7
docker stop server2-php7
docker stop server3-php7

#rehearsal
docker stop server1-php7-R
docker stop server2-php7-R
docker stop server3-php7-R

#development
docker stop server1-php7-D
docker stop server2-php7-D
docker stop server3-php7-D
